### ISSUE TITLE
Not able to download the dispute letter from discourse

### ISSUE THREAD

**Issue by dawn3296** [debtcollective/To-Do#10]
From discourse, when I click on the link to access the dispute letter. 
![image](https://user-images.githubusercontent.com/849872/61908043-5f8f7080-aef4-11e9-969b-e6966e9fa1b5.png)

the pop up tab goes to an OOPS message and the download does not happen.
![image](https://user-images.githubusercontent.com/42922071/61821486-34c9ed00-ae0c-11e9-96b1-dd2e278512ce.png)

here is an example account.
https://community.debtcollective.org/t/2242-mari-coffey-general-debt-dispute-creditors-bureau-usa/2606

It works if you download from the admin side. Just not the user/discourse side.

**Comment by orlando** [comment]
This is fixed on production. Links will render now like this, pointing to the right URL

![image](https://user-images.githubusercontent.com/849872/61912309-5b1c8500-aeff-11e9-9303-1b753408c90f.png)
