### ISSUE TITLE
Implement new designs for the landing page

### ISSUE THREAD

**Issue by orlando** [debtcollective/To-Do#4]
We have two new webinar video we want to put in the landing page. These videos explain the platform and what you have access when you join The Debt Collective.

A new landing page design including the video is available on Figma

## Acceptance Criteria

- Make updates to the landing page to look like the new design.

**Comment by orlando** [comment]
We have an upcoming design that will extend the scope of this ticket. I'll update it with the new information once we get the designs

**Comment by duranmla** [comment]
Designs to be implemented at https://www.figma.com/file/aT5c26DXxw7zx9eyV6Z6wpUx/Landing-Page-v2?node-id=0%3A1 _(I mention that here in order to make explicit and because I cant edit the issue)_

**Comment by duranmla** [comment]
The second point is that I am assuming the project I have to touch is this one https://github.com/debtcollective/landingpage _(may be silly but next time it would be great to add the ticket there or mention the repo within the ticket)_
